name: chauffeur
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.5.3
  cool_alert: ^2.0.1
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.2
  dot_navigation_bar: ^1.0.1+4
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  firebase_storage: ^11.1.1
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.4
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.2.8
  flutter_neumorphic: ^3.2.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.2.1
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  blurrycontainer: ^1.0.2
  sms_autofill: ^2.3.0
  google_sign_in: ^6.1.0
  image_picker: ^0.8.5+3
  like_button: ^2.0.4
  loading_animation_widget: ^1.2.0+2
  location: ^4.4.0
  multi_image_layout: ^0.0.5
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  provider: ^6.0.3
  quickalert: ^1.0.0
  rename: ^2.0.1
  search_page: ^2.0.0+1
  shimmer: ^2.0.0
  sign_button: ^2.0.2
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#f5f6f9"
    theme_color: "#f5f6f9"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
